/*QUERY to find top 10 spam accounts from the EMAIL_SPAM database*/
SELECT FROM_EMAIL, COUNT(*) AS EMAILS_SENT
FROM EMAIL_SPAM
GROUP BY FROM_EMAIL
ORDER BY EMAILS_SENT DESC
LIMIT 10;

/*QUERY to find top 10 ham accounts from the EMAIL_HAM database*/
SELECT FROM_EMAIL, COUNT(*) AS EMAILS_SENT
FROM EMAIL_HAM
GROUP BY FROM_EMAIL
ORDER BY EMAILS_SENT DESC
LIMIT 10;